LMS_SYSTEM/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from .views import home_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),  # for file upload
    
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('module_group/', include('module_group.urls')),  
    path('subject/', include('subject.urls')), 
    path('student_materials/', include('student_materials.urls')),
    path('training_program/', include('training_program.urls')),
    
    #group01
    path('user/', include(('user.urls', 'user'), namespace='user')),  # Register user app URLs with a namespace
    path('role/', include(('role.urls', 'user'))),
    path('department/', include(('department.urls', 'department'))),

    #group02
    path('course/', include('course.urls')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('forum/', include('forum.urls', namespace='forum')),

    #group03
    path('quiz/', include('quiz.urls')),  
    path('std_quiz/', include('std_quiz.urls')),
    path('course_Truong/', include('course_Truong.urls')),
    path('tools/', include('tools.urls')),
    

    #group04
    path('chat/', include('chat.urls')),
    path('chatapp/', include('chatapp.urls')),
    path('thread/', include('thread.urls')),
    path('collaboration_group/', include('collaboration_group.urls')),

    #group05
    path('activity/', include('activity.urls', namespace='activity')),  # Ensure this line exists
    path('certificate/', include('certificate.urls')),
    path('ai_insights', include('ai_insights.urls')),
    path('analytics_report', include('analytics_report.urls')),
    path('assignment', include('assignment.urls')),
    # path('course_completion', include('course_completion.urls')),

    path('performance_analytics', include('performance_analytics.urls')),
    path('progress_notification', include('progress_notification.urls')),
    path('student_performance', include('student_performance.urls')),
    path('user_progress', include('user_progress.urls')),
    path('user_summary', include('user_summary.urls')),
    path('book', include('book.urls')),


    #group06 - Binh_Thang - Coding
    path('exercises/', include('exercises.urls')), 
    path('assessments/', include('assessments.urls')),
    path('reports/', include('reports.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.book_search_view, name='book_search'),
    path('<str:book_id>/', views.book_detail_view, name='book_detail'),
]

course_Truong/urls.py
from django.urls import path
from .views import course_management
from .views import sub_course_management
from .views import module_management
from .views import sub_module_management
from .views import quiz_management
from .views import question_management
from .views import answer_management
from .views import course_operations
from .views import quiz_operations
from .views import image_management



app_name = 'course_Truong'

urlpatterns = [
    path('course_list',course_management.course_list,name='course_list'),

    path('upload_existed_course/',course_management.upload_existed_course,name='upload_existed_course'),
    path('course_add/',course_management.course_add,name='course_add'),
    path('course_edit/<int:course_pk>/',course_management.course_edit,name='course_edit'),
    path('course_delete/<int:course_pk>/',course_management.course_delete,name='course_delete'),
    path('<int:course_pk>/course_view/',course_management.course_view,name='course_view'),

    path('<int:course_pk>/image_list/',image_management.image_list,name='image_list'),
    path('<int:course_pk>/image_add/',image_management.image_add,name='image_add'),
    path('<int:course_pk>/image/<int:image_pk>/delete',image_management.image_delete,name='image_delete'),

    path('<int:course_pk>/sub_course/list/',sub_course_management.sub_course_list,name='sub_course_list'),
    path('<int:course_pk>/sub_course/add/',sub_course_management.sub_course_add,name='sub_course_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/edit',sub_course_management.sub_course_edit,name='sub_course_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/delete',sub_course_management.sub_course_delete,name='sub_course_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/move_up',sub_course_management.sub_course_move_up,name='sub_course_move_up'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/move_down',sub_course_management.sub_course_move_down,name='sub_course_move_down'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/add',module_management.module_add,name='module_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/edit',module_management.module_edit,name='module_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/delete',module_management.module_delete,name='module_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/move_up',module_management.module_move_up,name='module_move_up'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/move_down',module_management.module_move_down,name='module_move_down'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/sub_module/add',sub_module_management.sub_module_add,name='sub_module_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/sub_module/<int:sub_module_pk>/edit',sub_module_management.sub_module_edit,name='sub_module_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/sub_module/<int:sub_module_pk>/delete',sub_module_management.sub_module_delete,name='sub_module_delete'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/add',quiz_management.quiz_add,name='quiz_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/detail/',quiz_management.quiz_detail,name='quiz_detail'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/edit/',quiz_management.quiz_edit,name='quiz_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/delete/',quiz_management.quiz_delete,name='quiz_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/move_up/',quiz_management.quiz_move_up,name='quiz_move_up'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/move_down/',quiz_management.quiz_move_down,name='quiz_move_down'),


    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/add',question_management.question_add,name='question_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/delete',question_management.question_delete,name='question_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/edit',question_management.question_edit,name='question_edit'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/answer/add',answer_management.answer_add,name='answer_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/answer/<int:answer_pk>/edit',answer_management.answer_edit,name='answer_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/answer/<int:answer_pk>/delete',answer_management.answer_delete,name='answer_delete'),
    
    
    path('<int:course_pk>',course_operations.short_link_course,name='short_link_course'),
    path('<int:course_pk>/<str:course_name>/preview/',course_operations.course_preview,name='course_preview'),
    path('<int:course_pk>/enroll',course_operations.course_enroll,name='course_enroll'),

    path('<int:course_pk>/learn/<int:sub_module_pk>/',course_operations.short_link_learning_view,name='short_link_learning_view'),
    path('<int:course_pk>/<str:course_name>/learn/<int:sub_module_pk>',course_operations.learning_view,name='learning_view'),

    path('<int:course_pk>/quiz_preview/<int:quiz_pk>/',quiz_operations.short_link_quiz_preview,name='short_link_quiz_preview'),
    path('<int:course_pk>/<str:course_name>/quiz_preview/<int:quiz_pk>',quiz_operations.quiz_preview,name='quiz_preview'),

    path('<int:course_pk>/do_quiz/<int:quiz_pk>/',quiz_operations.short_link_do_quiz,name='short_link_do_quiz'),
    path('<int:course_pk>/<str:course_name>/do_quiz/<int:quiz_pk>',quiz_operations.do_quiz,name='do_quiz'),

    path('<int:course_pk>/quiz/<int:quiz_pk>/preview/<int:attempt_pk>',quiz_operations.short_link_attempted_quiz_preview,name='short_link_attempted_quiz_preview'),
    path('<int:course_pk>/<str:course_name>/quiz/<int:quiz_pk>/preview/<int:attempt_pk>',quiz_operations.attempted_quiz_preview,name='attempted_quiz_preview'),
]

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.quiz_list, name='quiz_list'),
    path('add/', views.quiz_add, name='quiz_add'),
    path('edit/<int:pk>/', views.quiz_edit, name='quiz_edit'),
    path('delete/<int:pk>/', views.quiz_delete, name='quiz_delete'),
    path('question_add/<int:pk>/', views.quiz_question, name='quiz_question'),
    path('detail/<int:quiz_id>/', views.quiz_detail, name='quiz_detail'),

    path('question/add/<int:quiz_id>/', views.question_add, name='question_add'),
    path('question/edit/<int:question_id>/', views.question_edit, name='question_edit'),
    path('quiz/question/delete/<int:pk>/', views.question_delete, name='question_delete'),
    path('question/detail/<int:pk>/', views.question_detail, name='question_detail'),

    #path('answer_option/add/<int:question_pk>/', views.answer_option_add, name='answer_option_add'),
    path('answer_option/edit/<int:pk>/', views.answer_option_edit, name='answer_option_edit'),
    path('answer_option/delete/<int:pk>/', views.answer_option_delete, name='answer_option_delete'),
    path('<int:quiz_id>/take/', views.take_quiz, name='take_quiz'),
    path('<int:quiz_id>/send_invite/', views.send_quiz_invite, name='send_invite'),
    path('<int:quiz_id>/copy_public_link/', views.copy_public_invite_link, name='copy_public_link'),
    path('<int:quiz_id>/take_public/', views.take_quiz_public, name='take_quiz_public'), # Đường dẫn cho public


    path('<int:quiz_id>/result/<int:attempt_id>/', views.quiz_result, name='quiz_result'),
    path('<int:quiz_id>/import/', views.import_questions, name='import_questions'),

    path('<int:quiz_id>/export/', views.export_questions, name='export_questions'),
    path('export/<str:format>/', views.export_quizzes, name='export_quizzes'),
    path('import/', views.import_quizzes, name='import_quizzes'),
    path('excel_to_json_view/',views.excel_to_json_view , name='excel_to_json_view'),
    path('get_answers/<int:question_pk>/', views.get_answers, name='get_answers'),
]

course_Truong/views/answer_management.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from module_group.models import ModuleGroup

from ..forms import Course_Form, Quiz_Form, Question_Form, Answer_Option_Form
from ..models import NewCourse, Quiz, Question, Answer_Option, Sub_Course

from django.contrib.auth.decorators import login_required, user_passes_test
from main.utils.block import block_student


@login_required
@user_passes_test(block_student)
def answer_add(request, course_pk, sub_course_pk, quiz_pk, question_pk):
    course = get_object_or_404(NewCourse, pk=course_pk)
    sub_course = get_object_or_404(Sub_Course, pk=sub_course_pk)
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    question = get_object_or_404(Question, pk=question_pk)

    if request.method == 'POST':
        form = Answer_Option_Form(request.POST)

        form.instance.question = question
        
        if form.is_valid():
            form = form.save()
            Quiz.objects.get(pk=quiz_pk).save()

            return redirect(reverse('course_Truong:quiz_detail', kwargs={'course_pk': course_pk, 'sub_course_pk': sub_course_pk, 'quiz_pk': quiz_pk}))
    else:
        form = Answer_Option_Form()

    context = {
        'form': form,
        'course_pk' : course_pk,
        'sub_course_pk' : sub_course_pk,
        'quiz_pk' : quiz_pk,
    }
    return render(request, 'answer_management/answer_form.html', context)


@login_required
@user_passes_test(block_student)
def answer_edit(request, course_pk, sub_course_pk, quiz_pk, question_pk, answer_pk):
    course = get_object_or_404(NewCourse, pk=course_pk)
    sub_course = get_object_or_404(Sub_Course, pk=sub_course_pk)
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    question = get_object_or_404(Question, pk=question_pk)
    answer = get_object_or_404(Answer_Option, pk=answer_pk)

    if request.method == 'POST':
        form = Answer_Option_Form(request.POST, instance=answer)

        if form.is_valid():
            form = form.save()
            Quiz.objects.get(pk=quiz_pk).save()

            return redirect(reverse('course_Truong:quiz_detail', kwargs={'course_pk': course_pk, 'sub_course_pk': sub_course_pk, 'quiz_pk': quiz_pk}))
    else:
        form = Answer_Option_Form(instance=answer)

    context = {
        'form': form,
        'course_pk' : course_pk,
        'sub_course_pk' : sub_course_pk,
        'quiz_pk' : quiz_pk,
    }
    return render(request, 'answer_management/answer_form.html', context)


@login_required
@user_passes_test(block_student)
def answer_delete(request, course_pk, sub_course_pk, quiz_pk, question_pk, answer_pk):
    course = get_object_or_404(NewCourse, pk=course_pk)
    sub_course = get_object_or_404(Sub_Course, pk=sub_course_pk)
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    question = get_object_or_404(Question, pk=question_pk)
    answer = get_object_or_404(Answer_Option, pk=answer_pk)

    if request.method == 'POST':
        answer.delete()
        Quiz.objects.get(pk=quiz_pk).save()

        return redirect(reverse('course_Truong:quiz_detail', kwargs={'course_pk': course_pk, 'sub_course_pk': sub_course_pk, 'quiz_pk': quiz_pk}))
    
    context = {
        'name': answer.option_text,
        'cancel_link': reverse('course_Truong:quiz_detail', kwargs={'course_pk': course_pk, 'sub_course_pk': sub_course_pk, 'quiz_pk': quiz_pk})
    }
    return render(request, 'confirm_delete.html', context)

course_Truong/views/image_management.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.core.cache import cache

from module_group.models import ModuleGroup

from ..forms import Image_Form
from ..models import NewCourse, Image

from django.contrib.auth.decorators import login_required, user_passes_test
from main.utils.block import block_student


@login_required
@user_passes_test(block_student)
def image_list(request, course_pk):
    course = get_object_or_404(NewCourse, pk=course_pk)
    images = course.images.all()
    print(images)
    module_groups = ModuleGroup.objects.all()

    context = {
        'module_groups' : module_groups,
        "course" : course,
        "images" : images,
    }
    return render(request, 'image_management/image_list.html', context)


@login_required
@user_passes_test(block_student)
def image_add(request, course_pk):
    course = get_object_or_404(NewCourse, pk= course_pk)

    if request.method == 'POST':
        for img in request.FILES.getlist('images'):
            Image.objects.create(image=img, course=course)
        return redirect(reverse('course_Truong:image_list', kwargs={'course_pk': course_pk}))
    # else:
    #     pass

    context = {
        'course_pk' : course_pk
    }
    return render(request, 'image_management/image_form.html', context)


@login_required
@user_passes_test(block_student)
def image_delete(request, course_pk, image_pk):
    course = get_object_or_404(NewCourse, pk=course_pk)
    image = get_object_or_404(Image, pk=image_pk)

    if request.method == 'POST':
        image.delete()
        return redirect(reverse('course_Truong:image_list', kwargs={'course_pk': course_pk}))
    
    context = {
        'name': image.image,
        'cancel_link': reverse('course_Truong:image_list', kwargs={'course_pk': course_pk})
    }
    return render(request, 'confirm_delete.html', context)

course_Truong/views/utils.py
def query_all_sub_courses(course, context:dict):
    sub_courses = course.sub_courses.all()
    for sub_course in sub_courses:
        modules = sub_course.modules.all().order_by("order")
        quizzes = sub_course.quizzes.all().order_by("order")
        
        context['sub_courses'][sub_course] = {
            'modules': {},
            'quizzes': quizzes,
        }

        for module in modules:
            sub_modules = module.sub_modules.all().order_by("order")

            context['sub_courses'][sub_course]['modules'][module] = sub_modules

course_Truong/templates/quiz_management/quiz_collapse.html
<div class="accordion my-2" id="accordionExample">
    {% for quiz in modules_and_quizzes.quizzes %}
    <div class="card">
      <div class="card-header" id="quiz_heading_{{ quiz.pk }}">
        <h2 class="mb-0">
          <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#quiz_collapse_{{ quiz.pk }}" aria-expanded="false" aria-controls="quiz_collapse_{{ quiz.pk }}">
            {{ quiz.order }}. {{ quiz.quiz_title }}
          </button>
        </h2>
      </div>
      <div id="quiz_collapse_{{ quiz.pk }}" class="collapse" aria-labelledby="quiz_heading_{{ quiz.pk }}" data-parent="#accordionExample">
        <div class="card-body">
            <h4 class="mb-4">Quiz Information</h4>
            <div class="row">
                <div class="col-7">
                    <p><strong>Title</strong>: {{ quiz.quiz_title }}</p>
                    <p><strong>Description</strong>: {{ quiz.quiz_description }}</p>
                    <p><strong>Total Mark</strong>: {{ quiz.total_mark }}</p>
                </div>
                <div class="col-5">
                    <p><strong>Created by</strong>: {{ quiz.created_by.full_name }}</p>
                    <p><strong>Created At</strong>: {{ quiz.created_at }}</p>
                    <p><strong>Updated at</strong>: {{ quiz.updated_at }}</p>
                </div>
            </div>
            <a href="{% url 'course_Truong:quiz_detail' course.pk sub_course.pk quiz.pk%}" style="width: 7rem;"
                        class="btn btn-primary">Detail</a>
            <a href="{% url 'course_Truong:quiz_move_up' course.pk sub_course.pk quiz.pk%}" style="width: 7rem;"
                        class="btn btn-success">Move Up</a>
            <a href="{% url 'course_Truong:quiz_move_down' course.pk sub_course.pk quiz.pk%}" style="width: 7rem;"
                        class="btn btn-warning">Move Down</a>
        </div>
      </div>
    </div>
{% endfor %}
</div>

course_Truong/templates/quiz_management/quiz_detail.html
{% extends 'base.html' %}
{% block title %}Course Detail{% endblock %}

{% block content %}
<div class="container mt-4">
    <h3 class="mb-4">Quiz Information</h3>
    <div class="row">
        <div class="col">
            <p><strong>Title: </strong>{{ quiz.quiz_title }}</p>
            <p><strong>Description: </strong>{{ quiz.quiz_description }}</p>
            <p><strong>Total Mark: </strong>{{ quiz.total_mark }}</p>
            <p><strong>Mark To Pass</strong>: {{ quiz.mark_to_pass }}</p>
        </div>
        <div class="col">
            <p><strong>Created by: </strong>{{ quiz.created_by.full_name }}</p>
            <p><strong>Created At: </strong>{{ quiz.created_at }}</p>
            <p><strong>Updated at: </strong>{{ quiz.updated_at }}</p>
        </div>
    </div>
    <a href="{% url 'course_Truong:quiz_edit' course.pk sub_course.pk quiz.pk%}" style="width: 5rem;"
        class="btn btn-primary">Edit</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th style="width: 5%;" scope="col">#</th>
                <th style="width: 95%;" scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for question, answers in questions_and_answers.items %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>
                    <h5><strong>Question: </strong>{{question.question_text}}</h5>
                    <p><strong>Type: </strong>{{question.question_type}}</p>
                    <p><strong>Points: </strong>{{question.points}}</p>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th style="width: 5%;" scope="col">#</th>
                                <th style="width: 70%;" scope="col">Answer</th>
                                <th style="width: 15%;" scope="col">Is Correct</th>
                                <th style="width: 10%;" scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for answer in answers %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{answer.option_text}}</td>
                                <td>{{answer.is_correct}}</td>
                                <td>
                                    <div class="dropdown">
                                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button"
                                            data-toggle="dropdown" aria-expanded="false">
                                            ...
                                        </a>
                                        <div class="dropdown-menu">
                                            <a href="{% url 'course_Truong:answer_edit' course.pk sub_course.pk quiz.pk question.pk answer.pk %}"
                                                class="dropdown-item">Edit</a>
                                            <a href="{% url 'course_Truong:answer_delete' course.pk sub_course.pk quiz.pk question.pk answer.pk %}"
                                                class="dropdown-item">Delete</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <a href="{% url 'course_Truong:answer_add' course.pk sub_course.pk quiz.pk question.pk%}" class="btn btn-primary">Add
                        Answer</a>
                    <hr>
                    <a href="{% url 'course_Truong:question_edit' course.pk sub_course.pk quiz.pk question.pk%}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'course_Truong:question_delete' course.pk sub_course.pk quiz.pk question.pk%}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'course_Truong:question_add' course.pk sub_course.pk quiz.pk%}" class="btn btn-primary">Add Question</a>


    <hr>
    <a href="{% url 'course_Truong:sub_course_list' course.pk %}" class="btn btn-secondary">Back to sub course List</a>
    <a href="{% url 'course_Truong:quiz_delete' course.pk sub_course.pk quiz.pk%}" class="btn btn-danger">Delete This
        Quiz!</a>
</div>
{% endblock %}

course_Truong/templates/quiz_management/quiz_form.html
{% extends 'base.html' %}
{% load form_filters %}
{% block title %}{% if form.instance.pk %}Edit Course{% else %}Add New Course{% endif %}{% endblock %}

{% block content %}
<div class="container mt-4">
    {% load form_filters %}

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.quiz_title.label_tag }}
            {{ form.quiz_title|add_class:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.quiz_description.label_tag }}
            {{ form.quiz_description|add_class:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.total_mark.label_tag }}
            {{ form.total_mark|add_class:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.mark_to_pass.label_tag }}
            {{ form.mark_to_pass|add_class:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
        
        {% if quiz_pk %}
        <a href="{% url 'course_Truong:quiz_detail' course_pk sub_course_pk quiz_pk %}" class="btn btn-secondary">Back</a>
        {% else %}
            <a href="{% url 'course_Truong:sub_course_list' course_pk %}" class="btn btn-secondary">Back</a>
        {% endif %}
    </form>
</div>
{% endblock %}

course_Truong/templates/quiz_management/quiz_list.html
{% extends 'base.html' %}
{% block title %}Course Detail{% endblock %}

{% block content %}
<div class="container mt-4">
    {% include "course_management/nav_tab.html" %}
    <div class="row">
        <div class="col-2">
            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                {% for quiz in quizzes %}
                <button class="nav-link {% if forloop.counter == 1 %}active{% endif %} text-left w-100 text-truncate"
                    id="quiz_id_{{ quiz.pk }}_tab" data-toggle="pill" data-target="#quiz_id_{{ quiz.pk }}" type="button"
                    role="tab" aria-controls="quiz_id_{{ quiz.pk }}"
                    aria-selected="{% if forloop.counter == 1 %}true{% else %}false{% endif %}">
                    {{ quiz.quiz_title }}
                </button>

                {% endfor %}

            </div>
        </div>
        <div class="col-10">
            <div class="tab-content" id="v-pills-tabContent">
                {% for quiz in quizzes %}
                <div class="tab-pane fade show {% if forloop.counter == 1 %}active{% endif %} pl-4"
                    id="quiz_id_{{ quiz.pk }}" role="tabpanel" aria-labelledby="quiz_id_{{ quiz.pk }}_tab"
                    style="border-left: solid 1px black;">

                    <h3 class="mb-4">Quiz Information</h3>
                    <p><strong>Title</strong>: {{ quiz.quiz_title }}</p>
                    <p><strong>Description</strong>: {{ quiz.quiz_description }}</p>
                    <p><strong>Total Mark</strong>: {{ quiz.total_mark }}</p>
                    <p><strong>Created by</strong>: {{ quiz.created_by.full_name }}</p>
                    <p><strong>Created At</strong>: {{ quiz.created_at }}</p>
                    <p><strong>Updated at</strong>: {{ quiz.updated_at }}</p>

                    <a href="{% url 'course_Truong:quiz_detail' course.pk quiz.pk%}" style="width: 5rem;"
                        class="btn btn-primary">Edit</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <a href="{% url 'course_Truong:quiz_add' course.pk%}" class="btn btn-primary">Add Quiz</a>
    <a href="{% url 'course_Truong:course_list' %}" class="btn btn-secondary">Back</a>
</div>
{% endblock %}