LMS_SYSTEM/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from .views import home_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),  # for file upload
    
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('module_group/', include('module_group.urls')),  
    path('subject/', include('subject.urls')), 
    path('student_materials/', include('student_materials.urls')),
    path('training_program/', include('training_program.urls')),
    
    #group01
    path('user/', include(('user.urls', 'user'), namespace='user')),  # Register user app URLs with a namespace
    path('role/', include(('role.urls', 'user'))),
    path('department/', include(('department.urls', 'department'))),

    #group02
    path('course/', include('course.urls')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('forum/', include('forum.urls', namespace='forum')),

    #group03
    path('quiz/', include('quiz.urls')),  
    path('std_quiz/', include('std_quiz.urls')),
    path('course_Truong/', include('course_Truong.urls')),
    path('tools/', include('tools.urls')),
    

    #group04
    path('chat/', include('chat.urls')),
    path('chatapp/', include('chatapp.urls')),
    path('thread/', include('thread.urls')),
    path('collaboration_group/', include('collaboration_group.urls')),

    #group05
    path('activity/', include('activity.urls', namespace='activity')),  # Ensure this line exists
    path('certificate/', include('certificate.urls')),
    path('ai_insights', include('ai_insights.urls')),
    path('analytics_report', include('analytics_report.urls')),
    path('assignment', include('assignment.urls')),
    # path('course_completion', include('course_completion.urls')),

    path('performance_analytics', include('performance_analytics.urls')),
    path('progress_notification', include('progress_notification.urls')),
    path('student_performance', include('student_performance.urls')),
    path('user_progress', include('user_progress.urls')),
    path('user_summary', include('user_summary.urls')),
    path('book', include('book.urls')),


    #group06 - Binh_Thang - Coding
    path('exercises/', include('exercises.urls')), 
    path('assessments/', include('assessments.urls')),
    path('reports/', include('reports.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.book_search_view, name='book_search'),
    path('<str:book_id>/', views.book_detail_view, name='book_detail'),
]

course/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'course'
urlpatterns = [
    path('', views.course_list, name='course_list'),
    path('add/', views.course_add, name='course_add'),
    path('edit/<int:pk>/', views.course_edit, name='course_edit'),
    path('courses/delete/<int:pk>/', views.course_delete, name='course_delete'),
    path('enroll/<int:pk>/', views.course_enroll, name='course_enroll'),
    path('unenroll/<int:pk>/', views.course_unenroll, name='course_unenroll'),
    path('<int:pk>/detail/', views.course_detail, name='course_detail'),
    path('<int:pk>/enrolled/', views.users_enrolled, name='users_enrolled'),
    path('search/', views.course_search, name='course_search'),
    # Content
    path('<int:pk>/content/<int:session_id>/', views.course_content, name='course_content'),
    path('<int:pk>/content/edit/<int:session_id>/', views.course_content_edit, name='course_content_edit'),
    #Export/Import
    path('export/', views.export_course, name='export_course'),
    path('import/', views.import_courses, name='import_course'),
    path('course/<int:pk>/toggle_publish/', views.toggle_publish, name='toggle_publish'),
    path('<int:pk>/toggle-completion/', views.toggle_completion, name='toggle_completion'),
    # Material
    path('edit/<int:pk>/reorder/<int:session_id>/', views.reorder_course_materials, name='reorder_course_materials'),
    path('reading-material/<int:id>/', views.reading_material_detail, name='reading_material_detail'),
    path('<int:pk>/content/edit/<int:session_id>/<int:reading_material_id>/edit/', views.edit_reading_material, name='edit_reading_material'),
    # Certificate
    path('<int:pk>/generate-certificate/', views.generate_certificate_png, name='generate_certificate'),
    # Topic URLs
    path('topics/', views.topic_list, name='topic_list'),
    path('topics/add/', views.topic_add, name='topic_add'),
    path('topics/edit/<int:pk>/', views.topic_edit, name='topic_edit'),
    path('topics/delete/<int:pk>/', views.topic_delete, name='topic_delete'),

    # Tag URLs
    path('tags/', views.tag_list, name='tag_list'),
    path('tags/add/', views.tag_add, name='tag_add'),
    path('tags/edit/<int:pk>/', views.tag_edit, name='tag_edit'),
    path('tags/delete/<int:pk>/', views.tag_delete, name='tag_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

progress_notification/urls.py
from django.urls import path
from . import views
app_name = 'progress_notification'

urlpatterns = [
    path('', views.progress_notification_list, name='progress_notification_list'),
    path('/<int:id>/', views.progress_notification_detail, name='progress_notification_detail'),
    path('/create/', views.progress_notification_add, name='progress_notification_add'),
    path('/edit/<int:id>/', views.progress_notification_edit, name='progress_notification_edit'),
    path('/delete/<int:id>/', views.progress_notification_delete, name='progress_notification_delete'),
    path('/import/', views.import_progress_notification, name='import_progress_notification'),
    path('/export/', views.export_progress_notification, name='export_progress_notification'),
    path('notification/count/', views.unread_notification_count, name='unread_notification_count'),
    path('notifications/', views.notification_list, name='notification_list'),


]

progress_notification/models.py
from django.db import models
from user.models import User
from course.models import Course
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from quiz.models import StudentQuizAttempt
from certificate.models import Certificate

class ProgressNotification(models.Model):    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True, blank=True)
    notification_message = models.CharField(max_length=255, blank=True, null=True)
    notification_date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

@receiver(post_save, sender=StudentQuizAttempt)
def create_progress_notification(sender, instance, created, **kwargs):
    if created:
        message = f"You finished {instance.quiz.quiz_title} with a score of {instance.score}."
        
        ProgressNotification.objects.create(
            user=instance.user,
            course=instance.quiz.course, 
            notification_message=message
        )
@receiver(post_save, sender=Certificate)
def create_progress_notification_certificate(sender, instance, created, **kwargs):
    if created:
        message = f"Congratulations, Certificate is Ready!"
        
        ProgressNotification.objects.create(
            user=instance.user,
            course=instance.course, 
            notification_message=message
        )

@receiver(post_delete, sender=StudentQuizAttempt)
def delete_progress_notification(sender, instance, **kwargs):
    ProgressNotification.objects.filter(user=instance.user, course=instance.quiz.course).delete()

progress_notification/forms.py
from django import forms
from .models import ProgressNotification

# Form for creating and editing users
class ProgressNotificationForm(forms.ModelForm):
    class Meta:
        model = ProgressNotification
        fields = ['user', 'course', 'notification_message']

class ExcelImportForm(forms.Form):
    excel_file = forms.FileField(label="Upload Excel File")

progress_notification/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.forms.models import model_to_dict
from .models import ProgressNotification
from .forms import ProgressNotificationForm, ExcelImportForm
from django.contrib import messages
import pandas as pd
import openpyxl
from django.http import HttpResponse

# User views
def progress_notification_list(request):
    progress_notification = ProgressNotification.objects.all()
    return render(request, 'progress_notification_list.html', {'progress_notification': progress_notification})

def progress_notification_detail(request, id):
    progress_notification = ProgressNotification.objects.get(id=id)
    return render(request, 'progress_notification_detail.html', {'progress_notification': progress_notification})

def progress_notification_add(request):
    if request.method == 'POST':
        form = ProgressNotificationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('progress_notification:progress_notification_list')
    else:
        form = ProgressNotificationForm()
    return render(request, 'progress_notification_form.html', {'form': form})

def progress_notification_edit(request, id):
    progress_notification = get_object_or_404(ProgressNotification, id=id)
    if request.method == 'POST':
        form = ProgressNotificationForm(request.POST, instance=progress_notification)
        if form.is_valid():
            form.save()
            return redirect('progress_notification:progress_notification_list')
    else:
        form = ProgressNotificationForm(instance=progress_notification)
    return render(request, 'progress_notification_form.html', {'form': form})

def progress_notification_delete(request, id):
    notification = ProgressNotification.objects.get(id=id)
    if request.method == 'POST':
        notification.delete()
        return redirect('progress_notification:progress_notification_list')
    return render(request, 'progress_notification_confirm_delete.html', {'notification': notification})

def export_progress_notification(request):
    # Create a workbook and add a worksheet
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=lms_progress_notification.xlsx'
    
    workbook = openpyxl.Workbook()
    worksheet = workbook.active
    worksheet.title = 'Progress Notification'

    
    # Define the columns
    columns = ['course','username','notification_message','notification_date']
    worksheet.append(columns)
    
    # Fetch all users and write to the Excel file
    for progress_notification in ProgressNotification.objects.all():
        try:    
            worksheet.append([str(progress_notification.course), str(progress_notification.username), progress_notification.notification_message, str(progress_notification.notification_date)])
        except Exception as e:
            print(e)
    
    workbook.save(response)
    return response

def import_progress_notification(request):
    if request.method == 'POST':
        form = ExcelImportForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = request.FILES['excel_file']
            try:
                # Read the Excel file
                df = pd.read_excel(uploaded_file)
                notification_imported = 0  # Counter for users successfully imported

                # Loop over the rows in the DataFrame
                for index, row in df.iterrows():
                    username = row.get('username')
                    course = str(row.get("course"))
                    notification_message = row.get("notification_message")

                    print(f"Processing row: {username}, {course}, {notification_message}")  # Debugging

                    # Check if the user already exists
                    from user.models import User
                    from course.models import Course
                    username_id = User.objects.get(username=username).id
                    course_id = Course.objects.get(course=course).id

                    print(username_id, course_id)

                    if not ProgressNotification.objects.filter(username_id=username_id, course=course, notification_message=notification_message).exists():
                        # Create and save the new user
                        ProgressNotification.objects.create(
                            username_id=username_id,
                            course_id=course_id,
                            notification_message=notification_message,
                        )
                        notification_imported += 1
                        print(f"notification {username} created")  # Debugging
                    else:
                        messages.warning(request, f"notification '{username}' already exists. Skipping.")
                        print(f"notification {username} already exists")  # Debugging

                # Feedback message
                if notification_imported > 0:
                    messages.success(request, f"{notification_imported} notifications imported successfully!")
                else:
                    messages.warning(request, "No notifications were imported.")

            except Exception as e:
                messages.error(request, f"An error occurred during import: {e}")
                print(f"Error during import: {e}")  # Debugging

            return redirect('progress_notification:progress_notification_list')
    else:
        form = ExcelImportForm()

    return render(request, 'progress_notification_list.html', {'form': form})


from django.http import JsonResponse
from .models import ProgressNotification

def unread_notification_count(request):
    if request.user.is_authenticated:
        count = ProgressNotification.objects.filter(user=request.user, is_read=False).count()
        return JsonResponse({'count': count})
    else:
        return JsonResponse({'count': 0})
    
def notification_list(request):
    if request.user.is_authenticated:
        notifications = ProgressNotification.objects.filter(user=request.user).order_by('-notification_date')
        notifications.update(is_read=True)
        notifications = list(notifications[:6])

        return render(request, 'notification_list.html', {'notifications': notifications})
    else:
        return render(request, 'notification_list.html', {'notifications': []})

progress_notification/templates/notification_list.html
<a href="{% url 'progress_notification:progress_notification_list' %}" style="color: black;">
    <h1>Notifications</h1>
</a>
<ul>
    {% for notification in notifications %}
    <a href="{% url 'course:course_detail' notification.course.id %}" style="color: black;">
        <strong>{{notification.course}}</strong>
    </a>
    <li>
        {{ notification.notification_message }} - {{ notification.notification_date }}
        {% if not notification.is_read %}
            <strong>(Unread)</strong>
        {% endif %}
    </li>
    {% empty %}
        <li>No notifications.</li>
    {% endfor %}
</ul>

progress_notification/templates/progress_notification_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Insight{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Confirm Delete</h2>
    <p style="color: red;">Are you sure you want to delete notification?</p>
    <h2>Notification Details</h2>
    <p><strong>Username:</strong> {{ notification.user }}</p>
    <p><strong>Course:</strong> {{ notification.course }}</p>
    <p><strong>Insight Text:</strong> {{ notification.notification_message }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm Delete</button>
        <a href="{% url 'progress_notification:progress_notification_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

progress_notification/templates/progress_notification_detail.html
{% extends 'base.html' %}

{% block title %}{{ progress_notification.user }} Notification Details{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Notification Details</h2>
    <p><strong>Username:</strong> {{ progress_notification.user }}</p>
    <p><strong>Course:</strong> {{ progress_notification.course }}</p>
    <p><strong>Notification Message:</strong> {{ progress_notification.notification_message }}</p>
    <a href="{% url 'progress_notification:progress_notification_list' %}" class="btn btn-primary">Back to Notifications List</a>
</div>
{% endblock %}

progress_notification/templates/progress_notification_form.html
{% extends 'base.html' %}
{% load form_filters %}

{% block title %}{{ form.instance.pk|yesno:"Edit Notification,Add New Notification" }}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>{{ form.instance.pk|yesno:"Edit Notification,Add New Notification" }}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.user.label_tag }}
            {{ form.user|add_class:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.course.label_tag }}
            {{ form.course|add_class:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.notification_message.label_tag }}
            {{ form.notification_message|add_class:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'progress_notification:progress_notification_list' %}" class="btn btn-secondary">Back to Progress Notification List</a>
    </form>
</div>
{% endblock %}

progress_notification/templates/progress_notification_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Progress Notification List{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Progress Notification List</h2>
    <div class="mt-3">

        <a href="{% url 'progress_notification:progress_notification_add' %}" class="btn btn-primary" title="Add New Notification" data-toggle="tooltip">
          <i class="fas fa-plus"></i> Add Notification
        </a>
        <button class="btn btn-success" title="Import Notification from Excel" data-toggle="modal" data-target="#importModal" data-toggle="tooltip">
          <i class="fas fa-file-import"></i> Import
        </button>
  
        <a href="{% url 'progress_notification:export_progress_notification' %}" class="btn btn-secondary" title="Export Notification to Excel" data-toggle="tooltip">
          <i class="fas fa-file-export"></i> Export
        </a>
      </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Username</th>
                <th>Course</th>
                <th>Notification Message</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for notification in progress_notification %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ notification.user }}</td>
                <td>{{ notification.course }}</td>
                <td>{{ notification.notification_message }}</td>
                <td>
                    <a href="{% url 'progress_notification:progress_notification_detail' notification.id %}" class="btn btn-info btn-sm">Details</a>
                    <a href="{% url 'progress_notification:progress_notification_edit' notification.id %}" class="btn btn-warning btn-sm">Edit</a>
                    <a href="{% url 'progress_notification:progress_notification_delete' notification.id %}" class="btn btn-danger btn-sm">Delete</a>

                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<!-- Import Modal -->
<div class="modal fade" id="importModal" tabindex="-1" role="dialog" aria-labelledby="importModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="importModalLabel">Import Insights from Excel</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <!-- Import Form -->
          <form method="post" enctype="multipart/form-data" action="{% url 'progress_notification:import_progress_notification' %}">
          <div class="mb-4">
            <span>
              Please download and use the <a href="{% static 'excel/import_progress_notification.xlsx' %}" target="_blank">Excel template</a>. The Excel file must contain exactly one sheet with the required columns.
            </span>
          </div>
            {% csrf_token %}
            <p>
              <label for="id_excel_file">Upload Excel File:</label>
              <input type="file" name="excel_file" required="" aria-invalid="true" id="id_excel_file">
            </p>
            <div class="form-group">
              <button type="submit" class="btn btn-primary">Upload</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Initialize Bootstrap Tooltips -->
  <script>
    $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();
    });
  </script>
{% endblock %}